name: flake8 Lint

on: [push, pull_request]

jobs:
  notify:
    name: Notify telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: notify
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"

  build_exe:
    name: Build Exe File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            pytest-mock
            Eel

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./

      - uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ./dist/windows

  build_telegram_notify:
    needs: [notify, flake8-lint, build_exe]
    if: ${{ (needs.notify.result == 'success' && needs.flake8-lint.result == 'success' && needs.build_exe.result == 'success') && always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: Successful build

      - name: Fail
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: Failed build


